import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[url(/backgrounds/circuit.png)] bg-repeat bg-[#001d2f] text-white`}
      >
        {children}
      </body>
    </html>
  );
}
